### ISSUE TITLE
How do I uninstall dragenengine?

### ISSUE THREAD

**Issue by ChekPuk** [LordOfDragons/dragengine#11]
I was stupid enough to install dragonengine with sudo, this was really bad idea... How do I uninstall everything? Didn't found how to do it with scons.

**Comment by LordOfDragons** [comment]
You can uninstall any target individually with scons by appending "-c". So to uninstall you can run one of these commands:

- `scons -c install` => Remove all install targets and their dependencies
- `scons -c install-engine-runtime` => Remove all install engine targets which includes the game engine and all modules
- `scons -c install-igde-runtime` => Remove all install igde targets which includes the igde and editors

If you run `scons -h` you see all supported targets. Any can be reversed with "-c".

**Comment by LordOfDragons** [comment]
Out of curiosity... what went wrong? I did sudo scons installs before and had no troubles. Depending on what went wrong it could be fixed.

**Comment by ChekPuk** [comment]
Oh... Sorry, forget to write in op... Restless night :) 

I was installing 1.4 release from source tarball, after successful installation i decided to remove it. Command 'scons -c install' left headers in /usr/incude and /usr/dragenengine with subfolders. Maybe something else. How to do a complete deinstallation? 

Installing something in root not with package manager - is a crime, that's why it was bad idea. It's not safe and it's hard to keep tracking files, upgrading and so on.

Interface and the engine was terribly slow on my laptop on both, Intel and Nvidia, some examples crashed with some weird errors. As I understand - the engine is not ready for casual poking of guy like me. This was a reason not to build or try Dragenengine again.

**Comment by LordOfDragons** [comment]
I see. The source code is set up for developing modules and editors and creating distribution files. It is not intended to be used directly by end users.

Instead to use the game engine (as gamer) or create games (game developer) you do not use the game engine sources, instead you use the distribution packages. This way installing the engine goes through the package manager of your distribution and allows proper uninstalling as well as proper updating. That's the intended way to use the game engine both for players and game developers. In particular that's how casual poking at the game engine is supposed to be done. Building the engine source code is only required for a specific group of people with specific needs.

For this reasons "scons -c" is not going to remove all files. In particular it leaves behind directories. This is how SCons works. You can though easily remove these directories after running "scons -c" like this:
`rm -rf /usr/{include,lib,share}/{dragengine,deigde}`
Which are in total 6 directories that can be safely deleted recursively.

Can you also tell me what kind of CPU and GPU you are using? This would allow me to better understand what hardware configurations work or do not work.

**Comment by ChekPuk** [comment]
But script that I should download as a regular gamer/developer will install it in /opt, not a big difference. If it doesn't produce package to install it should run from users folder where it can be easily removed.

As for specs - here is my lspci
```
00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03)
00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3)
00:1c.2 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #3 (rev e3)
00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3)
00:1c.4 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #5 (rev e3)
00:1d.0 USB controller: Intel Corporation Wildcat Point-LP USB EHCI Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
00:1f.2 SATA controller: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] (rev 03)
00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
03:00.0 Network controller: Intel Corporation Wireless 3160 (rev 93)
04:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 840M] (rev a2)
```
The other laptop I tried was with Nvidia 1660ti, don't remember CPU, but acted very similar, slideshow in dstestproject and errors on others. Bad luck. Maybe I should try some other building options, but nah, not interesting.

**Comment by LordOfDragons** [comment]
You can install into a specific directory by using SCons parameter "prefix=path/to/directory" or using "custom.py" (examples in "dist.custom.py" and "dist.posix.custom.py", copy and adjust). That's what I use for active development. It would be possible to modify the default path in SCons. I'll consider it. That said the "install" target is for engine development and package building using sandboxing (SCons option "--install-sandbox=path/to/sandbox").

The GPU looks fine. You should have no troubles running DSTestProject on it (the least demanding example). If the result is so bad I suspect problems with the OpenGL driver. Please provide the log files mentioned above, then I can tell more. On my Laptop I've got nVidia GPU too so that by itself should not be the problem.

**Comment by LordOfDragons** [comment]
Wait a moment... I totally forgot. You are compiling from "master" branch, is that right? The master branch is currently in progress of working on a new feature and is not stable right now. If you use the master branch right now you are going to get into troubles. Please use the "stable" branch. It points to the v1.4 release. Stupid me that I did not think of this earlier.

**Comment by ChekPuk** [comment]
No, I was using 1.4 release. Ok. Tomorrow I give it another try, this time  I will write down all errors and logs to help you understand what's happening. In new issue?

As for this issue with complete removal I think that there must be a bit more in readme, or in manual.

**Comment by LordOfDragons** [comment]
It's certainly not wrong to create a new issue for these errors. Helps others looking for problems if issues are not mingled.

I've adjusted the README. More changes can be made if required.

**Comment by ChekPuk** [comment]
Oh... Installed install-dragengine-1.4-linux64.sh and install-deigde-1.4-linux64.sh... How do I remove them now? Scons provided -c option, but by installing with scripts I can't really know how to remove them back. This is wrong. I quit.

**Comment by LordOfDragons** [comment]
The uninstall option I've added for the 1.5 release. You can use them already now by getting the nightly build installers since their uninstallers work also for older installation. To uninstall run the installers with the "--uninstall" option: https://github.com/LordOfDragons/dragengine/releases/tag/nightly .

**Comment by LordOfDragons** [comment]
I'll close this issue since the information provided in here should be sufficient.

Concerning the running issues please create a new ticket and attach the above mentioned log files.
