### ISSUE TITLE
dragengine 1.11 build failure: missing 'engine/declEngine.h' file

### ISSUE THREAD

**Issue by kenmays** [LordOfDragons/dragengine#14]
When building on Haiku x86 w/ GCC 11.2.0:

URL: https://github.com/LordOfDragons/dragengine/blob/master/src/launcher/console/src/consolelauncher.cpp

```
Compiling src/launcher/console/src/consolelauncher.cpp
src/launcher/console/src/consolelauncher.cpp:54:10 fatal error: engine/declEngine.h: No such file or directory

#54 | #include "engine/declEngine.h"
```

**Comment by LordOfDragons** [comment]
Fixed with commit be551195e56274806a9072048a5cdf826c77ab56 , tag "v1.11-haiku2". Builds now again on VirtualBox image. Pull request https://github.com/haikuports/haikuports/pull/6786 .
