### ISSUE TITLE
Cannot be installed on Haiku R1 beta 2 64bit.

### ISSUE THREAD

**Issue by Brunobasta** [LordOfDragons/dragengine#6]
The Haiku package of the engine and the dev-engine cannot installed on my Haiku R1 beta 2 64bit version.
Not tried on 32bit yet, will report back soon...

Maybe you compiled for 32bit only?
Please ask the Haiku developer and Porter in #haiku IRC chat for quick response... it seems like a minor problem.
I am not a dev / porter so I might not very helpful here.

But I will test the program as soon as available as Hpkg again.
Nice work, seems to be a great project and very creative for game-devs.
Bruno

**Comment by LordOfDragons** [comment]
The Haiku I used for building the package is hrev54447 x86_64. This should yield a 64-bit build. But most probably the package script is wrong with x86 arch. I'll change this and re-upload.
